name: Build and Upload to TestFlight

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod install --repo-update

      - name: Archive (Runner workspace)
        run: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -archivePath ios/build/Runner.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ios/ExportOptions.plist
          cat ios/ExportOptions.plist

      - name: Prepare App Store Connect API key
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8
          chmod 600 ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath ios/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath ios/build/export \
            -allowProvisioningUpdates \
            -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8 \
            -authenticationKeyID ${{ secrets.APPLE_API_KEY_ID }} \
            -authenticationKeyIssuerID ${{ secrets.APPLE_API_ISSUER_ID }}

      - name: Upload to App Store Connect (iTMSTransporter)
        run: |
          xcrun iTMSTransporter -m upload -assetFile ios/build/export/Runner.ipa -apiKey ${{ secrets.APPLE_API_KEY_ID }} -apiIssuer ${{ secrets.APPLE_API_ISSUER_ID }} -v informational
